name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
#   push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Anant-mishra1729/metrics@master
        with:
          config_timezone: Asia/India
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: jupyter notebook, css
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_habits: yes
          plugin_followup: yes
          plugin_followup_sections: user, repositories
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          config_display: large
