name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Anant-mishra1729/metrics@master
        with:
          config_timezone: Asia/India
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          base: ""
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: jupyter notebook, css
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_display: compact
          config_display: large
